# Generated by Django 4.2.7 on 2023-11-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=50)),
                ('disc2', models.TextField()),
                ('img2', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
